/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IPL.League.Analysis;

public class LeagueAnalyser {
    public static void main(String[] args) {
    	System.out.println("Welcome To IPL LEague Analysis Problem!!!");
    }
}
